//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRemoteAccess")]
    public interface IRemoteAccess {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteAccess/RequestSql", ReplyAction="http://tempuri.org/IRemoteAccess/RequestSqlResponse")]
        string[] RequestSql(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteAccess/RequestSql", ReplyAction="http://tempuri.org/IRemoteAccess/RequestSqlResponse")]
        System.Threading.Tasks.Task<string[]> RequestSqlAsync(string sql);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRemoteAccessChannel : RemoteServiceClient.ServiceReference1.IRemoteAccess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemoteAccessClient : System.ServiceModel.ClientBase<RemoteServiceClient.ServiceReference1.IRemoteAccess>, RemoteServiceClient.ServiceReference1.IRemoteAccess {
        
        public RemoteAccessClient() {
        }
        
        public RemoteAccessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RemoteAccessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteAccessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteAccessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] RequestSql(string sql) {
            return base.Channel.RequestSql(sql);
        }
        
        public System.Threading.Tasks.Task<string[]> RequestSqlAsync(string sql) {
            return base.Channel.RequestSqlAsync(sql);
        }
    }
}
